version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-apache-stretch-browsers

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-php-vendor-{{ checksum "composer.lock" }}
        - v1-php-vendor-

    - run: composer install

    - save_cache:   
        key: v1-php-vendor-{{ checksum "composer.lock" }}
        paths:
        - vendors

    - run: vendor/bin/phpunit
    - run: composer validate --strict
    - run: vendor/bin/parallel-lint src tests
    - run: vendor/bin/php-cs-fixer fix --dry-run --verbose
    - run: vendor/bin/security-checker security:check

